### ISSUE TITLE
Отображение MapPolyline на карте

### ISSUE THREAD

**Issue by AlexeyRudakov** [yandexmobile/yandexmapkit-wp#1]
Доброго времени суток! Как нарисовать ломанную линию между тремя точками на карте (например: 55.756781, 37.603199    55.756781, 37.603299   55.756881, 37.603199) с помощью MapPolyline? Если есть такая возможность, приведите пожалуйста пример.

**Comment by kzaikin** [comment]
Сегодня обновился тестовый пример. Там есть страница, на которой показано использование MapPolyline
