### ISSUE TITLE
Цвет Pushpin, Кластеризация

### ISSUE THREAD

**Issue by omelics** [yandexmobile/yandexmapkit-wp#11]
Здравствуйте.
1. Нашёл как поменять цвет описания пушпина, а вот цвет самого пушпина поменять не получается. Подскажите, пожалуйста, как это можно сделать?
1. Когда можно будет использовать кластеризацию в Windows Phone MapKit? К сожалению, IE вообще никак не реагирует на интерактивность карты, распознаёт как обычный div.

Спасибо

**Comment by teshca** [comment]
В текщуей версии mapkit нет возможности изменять цвет пушпина
Но вы можете использовать свой собственный шаблон для вашего контрола, и таким образом изменять не только цвет но и форму.

Кластеризации в текущей версии mapkit нет. Информацию о сроках мы не разглашаем.

**Comment by omelics** [comment]
Спасибо.
