### ISSUE TITLE
Не загружает спутниковые карты

### ISSUE THREAD

**Issue by a-klimashevsky** [yandexmobile/yandexmapkit-wp#13]
WP 7.1 не подгружает тайлы спутниковых карт

**Comment by teshca** [comment]
Для того чтобы карта загружала тайлы спутниковых карт, необохимо указать ей свойство
DisplayLayers="sat,skl"

Попробуйте запустить тестовый пример, предварительно заменив в коде MapPage.xaml
строчку 
DisplayLayers="map"
на
DisplayLayers="sat,skl"

**Comment by a-klimashevsky** [comment]
Да, спасибо, если перечислять 2, то работает. а как загружать 2 уровня из кода?

**Comment by teshca** [comment]
map.DisplayLayers = BaseLayers.sat | BaseLayers.skl;
