### ISSUE TITLE
ZIndex Pushpin Content

### ISSUE THREAD

**Issue by sorochan** [yandexmobile/yandexmapkit-wp#15]
Привет!
Заметил такое поведение, когда на карте много объектов, выбираешь один из них, рядом стоящие точки показываются поверх, всплывающего контента выбранного объекта (не всегда,а в порядке добавления элементов на панель). Пробовал в момент изменения свойства "видимостиконтента" выставлять у выделенного элемента ZIndex - не помогло, как лучше поступить, подскажите пожалуйста.

**Comment by teshca** [comment]
Для того чтобы в вашем сценарии всё работало корректно вам необходимо:
1. Добавить PushPinZIndexBehavior к карте

```
                <i:Interaction.Behaviors>
                     ...
                    <Behavior:PushPinZIndexBehavior GroupKey="All"/>
                </i:Interaction.Behaviors>
```
1. Для всех ваших объектов добавить attached property

```
                <ymc:PushPin
                         ...
                         ymc:PushPinManagerHelper.GroupKeys="All" />
```

Подробный пример использования можно найти в тестовом примере в файле MapPage.xaml
