### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by wadimk** [yandexmobile/yandexmapkit-wp#16]
Привет! 

В примере для WP для геокодирования получаю exception в GeocodeFailed, сообщение "Bad GZIP header."

StackTrace  "   at Ionic.Zlib.ZlibBaseStream._ReadAndValidateGzipHeader()\r\n   at Ionic.Zlib.ZlibBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Ionic.Zlib.GZipStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.IO.StreamReader.ReadBuffer(Char[] userBuffer, Int32 userOffset, Int32 desiredChars, Boolean& readToUserBuffer)\r\n   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)\r\n   at System.Xml.XmlTextReaderImpl.ReadData()\r\n   at System.Xml.XmlTextReaderImpl.InitTextReaderInput(String baseUriStr, TextReader input)\r\n   at System.Xml.XmlTextReaderImpl..ctor(TextReader input, XmlReaderSettings settings, String baseUriStr, XmlParserContext context)\r\n   at System.Xml.XmlReader.CreateReaderImpl(TextReader input, XmlReaderSettings settings, String baseUriStr, XmlParserContext context)\r\n   at System.Xml.XmlReader.Create(TextReader input, XmlReaderSettings settings, String baseUri)\r\n   at System.Xml.XmlReader.Create(TextReader input, XmlReaderSettings settings)\r\n   at Yandex.Serialization.GenericXmlSerializer`1.DeserializeFromStream(Stream inputStream, XmlSerializer ser, XmlReaderSettings xmlReaderSettings)\r\n   at Yandex.Serialization.GenericXmlSerializer`1.Deserialize(Stream inputStream, Boolean leaveOpen)\r\n   at Yandex.WebUtils.CommunicatorBase`3.ProcessResultStream(GeocodeRequestParameters parameters, Stream stream)\r\n   at Yandex.WebUtils.CommunicatorBase`3.GetResponseCallback(IHttpWebRequest request, IAsyncResult asyncResult)\r\n   at Yandex.WebUtils.DefaultCommunicatorBase`3.<>c__DisplayClass1.<ExecuteInternal>b__0(IAsyncResult asyncResult)\r\n   at System.Net.Browser.ClientHttpWebRequest.<>c__DisplayClassa.<InvokeGetResponseCallback>b__8(Object state2)\r\n   at System.Threading.ThreadPool.WorkItem.WaitCallback_Context(Object state)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadPool.WorkItem.doWork(Object o)\r\n   at System.Threading.Timer.ring()\r\n"  string

**Comment by teshca** [comment]
Здравствуйте

На сколько стабильно у вас воспроизводится проблема? exception происходит на каких-то определённых координатах или на всех? Можете ли вы предоставить лог фидлера для запросов на которых происходит ошибка?

**Comment by wadimk** [comment]
Прошу прощения за задержку с ответом, был в отпуске. Сейчас проблема не воспроизводится.
