### ISSUE TITLE
Локализация для карт

### ISSUE THREAD

**Issue by happynik** [yandexmobile/yandexmapkit-wp#17]
Здравствуйте.
Планируется ли поддержка локализации карт?

здесь(https://github.com/yandexmobile/yandexmapkit-wp/issues/7) ответили, что локализация пока не поддерживается, но ответ был более года назад.

**Comment by ghost** [comment]
Здравствуйте!
Исходя из этой информации http://api.yandex.ru/mapkit/ поддержка текущей версии MapKit прекращена.
