### ISSUE TITLE
Please call UiDispatcher ctor from Ui thread

### ISSUE THREAD

**Issue by ceth-x86** [yandexmobile/yandexmapkit-wp#18]
Добрый день,

А работает ли YandexMapKit в Windows 8.1 Universal App?
При добавлении элемента карт на форму сразу появляется вот это сообщение "Please call UiDispatcher ctor from Ui thread".

В общем то, оно не мешает работать, но дальше появляются другие проблемы и прежде чем их решать, хотелось бы понять, а возможно ли вообще работать с картами на Windows 8.1 и, в частности, расставлять PushPin - ы ?

**Comment by kzaikin** [comment]
Работа мапкита в Windows 8.1 не проверялась. Но если заведётся, то пушпины будут работать. Примеры см. для WP, XAML или код будут аналогичные
