### ISSUE TITLE
Release version of Rx 2.0 is available

### ISSUE THREAD

**Issue by 3stark** [yandexmobile/yandexmapkit-wp#2]
When running Rx release 2:0:20823:0 throws:
File or assembly name 'System.Reactive.Linq, Version=2.0.20612.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35', or one of its dependencies, was not found.

**Comment by kzaikin** [comment]
Will submit an update using release Rx

**Comment by iamruss** [comment]
Yes, please submit it. Thank you! :)

**Comment by kzaikin** [comment]
RX 2.0 is used now
