### ISSUE TITLE
Обратное геокодирование не работает если до этого не была ни разу показана карта с введенным apikey.

### ISSUE THREAD

**Issue by DiverOfDark** [yandexmobile/yandexmapkit-wp#3]
Падает в: 
      geocodeManager.Query(new GeocodeRequestParameters(new GeoCoordinate(Geo.Latitude, Geo.Longitude), null));
с ошибкой The URI prefix is not recognized., причем уже в > Yandex.Maps.dll!Yandex.WebUtils.WebClientFactory.CreateGetHttpWebRequest(System.Uri uri) + 0x8 bytes 
uri был +  uri {file:///mapkit/geocode%3Fll=55.8724002838135,37.5593204498291&ver=2&gzip=0%3Flang=ru-RU%3Frndwp=2e862d2c-f204-434f-aeda-a66384f6ec05} System.Uri

**Comment by kzaikin** [comment]
Fixed
