### ISSUE TITLE
API карт из коробки позволяет определить текущее местоположение пользователя?

### ISSUE THREAD

**Issue by uncledoc** [yandexmobile/yandexmapkit-wp#5]
При задании свойства UseLocation=true и при вызове JumpToCurrentLocation() на Lumia 800 и в эмуляторе - ничего не происходит.

**Comment by kzaikin** [comment]
В документации к свойство UseLocation сказано
Remarks
Warning! This property has no effect unless MapGlobalSettings.Instance.EnableLocationService property is true. 

Добавил отдельную страничку на вики:
https://github.com/yandexmobile/yandexmapkit-wp/wiki/Enable-Location-in-MapKit
